### ISSUE TITLE
Links to ODBC (all platforms) and Node.js (Windows) drivers are broken

### ISSUE THREAD

**Issue by sduncan01** [intersystems-community/iris-driver-distribution#29]
The links to download ODBC drivers for Ubuntu, Mac, and Windows at https://intersystems-community.github.io/iris-driver-distribution/ lead to status 404 error pages. This appears to be because the main branch of this repository doesn't contain the linked files - it looks like the driver versions have been updated in the repository but the links have not been updated.

Also, the link to download the Node.js driver for Windows has no effect - I see this error in the browser console when I click it:

Uncaught TypeError: document.getElementById(...) is null
iris-driver-distribution:1:10
onclick https://intersystems-community.github.io/iris-driver-distribution/:1

**Comment by semanej** [comment]
ODBC buttons have now been fixed in the distribution page. There's no Node.js driver for Windows so I've now removed that button
